### PR TITLE
Ubuntu base images are absurdly bloated

### PR DESCRIPTION
**Pull request by robbyoconnor**
debian:jessie images are much, much slimmer

### CODE REVIEW

**Comment by amazy** [comment]
@jodogne FYI:
debian:jessie : 123 MB
ubuntu:14.04: 189 MB
ubuntu:16.04: 129 MB

**Comment by robbyoconnor** [comment]
@jodogne, @amazy I'd always favor `debian:jessie`, there's also `debian:jessie-slim`.

**Comment by robbyoconnor** [comment]
Is there a reason to not use `alpine` though?

**Comment by jodogne** [comment]
I'm not really keen on changing the base image, as it is currently used in production, notably by @amazy.

**Comment by amazy** [comment]
Concerning alpine, this would probably require to adapt a few build scripts since the base libraries (libc, ...) are not the same.

The biggest problem with the current Docker image is not about the base image but about all the intermediate layers that are still part of the final Docker images.  That's why the Orthanc image is 800MB while the base Debian/Ubuntu are around 150MB.

We would need to build Orthanc on an image and then, copy the build artifacts to a clean ubuntu/debian image.

Going from ubuntu to debian/jessie would reduce the image size from 800MB to 750MB while changing the build process would reduce it from 800MB to 200MB (all Orthanc binaries are around 50MB).

So let's go for this deeper refactoring some day ...

**Comment by jodogne** [comment]
I think the issue is rather in the fact that the "build-essential" stuff (notably gcc) is not removed from the final images.

**Comment by tn-osimis** [comment]
The Docker image builder now offers an [experimental `--squash` option](https://docs.docker.com/engine/reference/commandline/build/#squash-an-images-layers---squash-experimental-only) that can be used to offload the build artefacts if they're properly removed in topmost layers.

However, it's probably best to wait a little more for [multi-stage build](http://training.play-with-docker.com/multi-stage/) which will allow doing what Alain suggested in a very straightforward way (just modifying the Dockerfile).

Regarding Alpine I did attempt a build at some point, but after a few minutes I realized this would require some focus which I couldn't afford at the time (I reckon it's *probably* a 1h job or something, if somebody wants to take a shot at it). I don't remember which dependencies were giving some trouble, but it's definitely doable (it might be easier now, too). Notice: All official Docker images use separate tags mirroring "normal" ones but suffixed `-alpine`, if we were to do the same this wouldn't break compatibility of course.

**Comment by robbyoconnor** [comment]
debian:jessie is what ubuntu is based off though -- so we could at least use that.

**Comment by jodogne** [comment]
The Orthanc images now weight only 115MB. They are based on `debian:wheezy-slim`, and contain binaries that are precompiled using the Linux Standard Base compiler, on the CIS of the Orthanc project. As a consequence, I close this pull request.

**Pull request closed without merging**
